/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssignPlaylistDto model module.
 * @module model/AssignPlaylistDto
 * @version 1.0
 */
class AssignPlaylistDto {
    /**
     * Constructs a new <code>AssignPlaylistDto</code>.
     * @alias module:model/AssignPlaylistDto
     * @param playlistId {Number} ID playlisty przypisywanej do ekranu
     */
    constructor(playlistId) { 
        
        AssignPlaylistDto.initialize(this, playlistId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playlistId) { 
        obj['playlistId'] = playlistId;
    }

    /**
     * Constructs a <code>AssignPlaylistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssignPlaylistDto} obj Optional instance to populate.
     * @return {module:model/AssignPlaylistDto} The populated <code>AssignPlaylistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssignPlaylistDto();

            if (data.hasOwnProperty('playlistId')) {
                obj['playlistId'] = ApiClient.convertToType(data['playlistId'], 'Number');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('activeFrom')) {
                obj['activeFrom'] = ApiClient.convertToType(data['activeFrom'], 'String');
            }
            if (data.hasOwnProperty('activeTo')) {
                obj['activeTo'] = ApiClient.convertToType(data['activeTo'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssignPlaylistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssignPlaylistDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssignPlaylistDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['activeFrom'] && !(typeof data['activeFrom'] === 'string' || data['activeFrom'] instanceof String)) {
            throw new Error("Expected the field `activeFrom` to be a primitive type in the JSON string but got " + data['activeFrom']);
        }
        // ensure the json data is a string
        if (data['activeTo'] && !(typeof data['activeTo'] === 'string' || data['activeTo'] instanceof String)) {
            throw new Error("Expected the field `activeTo` to be a primitive type in the JSON string but got " + data['activeTo']);
        }

        return true;
    }


}

AssignPlaylistDto.RequiredProperties = ["playlistId"];

/**
 * ID playlisty przypisywanej do ekranu
 * @member {Number} playlistId
 */
AssignPlaylistDto.prototype['playlistId'] = undefined;

/**
 * Priorytet przypisania
 * @member {Number} priority
 */
AssignPlaylistDto.prototype['priority'] = undefined;

/**
 * Data rozpoczęcia aktywności playlisty
 * @member {String} activeFrom
 */
AssignPlaylistDto.prototype['activeFrom'] = undefined;

/**
 * Data zakończenia aktywności playlisty
 * @member {String} activeTo
 */
AssignPlaylistDto.prototype['activeTo'] = undefined;






export default AssignPlaylistDto;

