/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateFileDto model module.
 * @module model/CreateFileDto
 * @version 1.0
 */
class CreateFileDto {
    /**
     * Constructs a new <code>CreateFileDto</code>.
     * @alias module:model/CreateFileDto
     * @param filename {String} 
     * @param originalName {String} 
     * @param path {String} 
     * @param mimeType {String} 
     * @param size {Number} 
     * @param checksum {String} 
     * @param duration {Number} 
     */
    constructor(filename, originalName, path, mimeType, size, checksum, duration) { 
        
        CreateFileDto.initialize(this, filename, originalName, path, mimeType, size, checksum, duration);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, filename, originalName, path, mimeType, size, checksum, duration) { 
        obj['filename'] = filename;
        obj['originalName'] = originalName;
        obj['path'] = path;
        obj['mimeType'] = mimeType;
        obj['size'] = size;
        obj['checksum'] = checksum;
        obj['duration'] = duration;
    }

    /**
     * Constructs a <code>CreateFileDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFileDto} obj Optional instance to populate.
     * @return {module:model/CreateFileDto} The populated <code>CreateFileDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFileDto();

            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('originalName')) {
                obj['originalName'] = ApiClient.convertToType(data['originalName'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('checksum')) {
                obj['checksum'] = ApiClient.convertToType(data['checksum'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateFileDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateFileDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateFileDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
            throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
        }
        // ensure the json data is a string
        if (data['originalName'] && !(typeof data['originalName'] === 'string' || data['originalName'] instanceof String)) {
            throw new Error("Expected the field `originalName` to be a primitive type in the JSON string but got " + data['originalName']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }
        // ensure the json data is a string
        if (data['checksum'] && !(typeof data['checksum'] === 'string' || data['checksum'] instanceof String)) {
            throw new Error("Expected the field `checksum` to be a primitive type in the JSON string but got " + data['checksum']);
        }

        return true;
    }


}

CreateFileDto.RequiredProperties = ["filename", "originalName", "path", "mimeType", "size", "checksum", "duration"];

/**
 * @member {String} filename
 */
CreateFileDto.prototype['filename'] = undefined;

/**
 * @member {String} originalName
 */
CreateFileDto.prototype['originalName'] = undefined;

/**
 * @member {String} path
 */
CreateFileDto.prototype['path'] = undefined;

/**
 * @member {String} mimeType
 */
CreateFileDto.prototype['mimeType'] = undefined;

/**
 * @member {Number} size
 */
CreateFileDto.prototype['size'] = undefined;

/**
 * @member {String} checksum
 */
CreateFileDto.prototype['checksum'] = undefined;

/**
 * @member {Number} duration
 */
CreateFileDto.prototype['duration'] = undefined;






export default CreateFileDto;

