/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileEntity model module.
 * @module model/FileEntity
 * @version 1.0
 */
class FileEntity {
    /**
     * Constructs a new <code>FileEntity</code>.
     * @alias module:model/FileEntity
     * @param id {Number} 
     * @param filename {String} 
     * @param originalName {String} 
     * @param path {String} 
     * @param mimeType {String} 
     * @param duration {Object} 
     * @param size {Number} 
     * @param checksum {Object} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param playlistItems {Array.<String>} 
     * @param screenAsFallback {Object} 
     */
    constructor(id, filename, originalName, path, mimeType, duration, size, checksum, createdAt, updatedAt, playlistItems, screenAsFallback) { 
        
        FileEntity.initialize(this, id, filename, originalName, path, mimeType, duration, size, checksum, createdAt, updatedAt, playlistItems, screenAsFallback);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, filename, originalName, path, mimeType, duration, size, checksum, createdAt, updatedAt, playlistItems, screenAsFallback) { 
        obj['id'] = id;
        obj['filename'] = filename;
        obj['originalName'] = originalName;
        obj['path'] = path;
        obj['mimeType'] = mimeType;
        obj['duration'] = duration;
        obj['size'] = size;
        obj['checksum'] = checksum;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['playlistItems'] = playlistItems;
        obj['screenAsFallback'] = screenAsFallback;
    }

    /**
     * Constructs a <code>FileEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileEntity} obj Optional instance to populate.
     * @return {module:model/FileEntity} The populated <code>FileEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('originalName')) {
                obj['originalName'] = ApiClient.convertToType(data['originalName'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], Object);
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('checksum')) {
                obj['checksum'] = ApiClient.convertToType(data['checksum'], Object);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('playlistItems')) {
                obj['playlistItems'] = ApiClient.convertToType(data['playlistItems'], ['String']);
            }
            if (data.hasOwnProperty('screenAsFallback')) {
                obj['screenAsFallback'] = ApiClient.convertToType(data['screenAsFallback'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FileEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FileEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FileEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
            throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
        }
        // ensure the json data is a string
        if (data['originalName'] && !(typeof data['originalName'] === 'string' || data['originalName'] instanceof String)) {
            throw new Error("Expected the field `originalName` to be a primitive type in the JSON string but got " + data['originalName']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['mimeType'] && !(typeof data['mimeType'] === 'string' || data['mimeType'] instanceof String)) {
            throw new Error("Expected the field `mimeType` to be a primitive type in the JSON string but got " + data['mimeType']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['playlistItems'])) {
            throw new Error("Expected the field `playlistItems` to be an array in the JSON data but got " + data['playlistItems']);
        }

        return true;
    }


}

FileEntity.RequiredProperties = ["id", "filename", "originalName", "path", "mimeType", "duration", "size", "checksum", "createdAt", "updatedAt", "playlistItems", "screenAsFallback"];

/**
 * @member {Number} id
 */
FileEntity.prototype['id'] = undefined;

/**
 * @member {String} filename
 */
FileEntity.prototype['filename'] = undefined;

/**
 * @member {String} originalName
 */
FileEntity.prototype['originalName'] = undefined;

/**
 * @member {String} path
 */
FileEntity.prototype['path'] = undefined;

/**
 * @member {String} mimeType
 */
FileEntity.prototype['mimeType'] = undefined;

/**
 * @member {Object} duration
 */
FileEntity.prototype['duration'] = undefined;

/**
 * @member {Number} size
 */
FileEntity.prototype['size'] = undefined;

/**
 * @member {Object} checksum
 */
FileEntity.prototype['checksum'] = undefined;

/**
 * @member {Date} createdAt
 */
FileEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
FileEntity.prototype['updatedAt'] = undefined;

/**
 * @member {Array.<String>} playlistItems
 */
FileEntity.prototype['playlistItems'] = undefined;

/**
 * @member {Object} screenAsFallback
 */
FileEntity.prototype['screenAsFallback'] = undefined;






export default FileEntity;

