/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileEntity from './FileEntity';
import PlaylistEntity from './PlaylistEntity';

/**
 * The PlaylistItemEntity model module.
 * @module model/PlaylistItemEntity
 * @version 1.0
 */
class PlaylistItemEntity {
    /**
     * Constructs a new <code>PlaylistItemEntity</code>.
     * @alias module:model/PlaylistItemEntity
     * @param id {Number} 
     * @param position {Number} 
     * @param duration {Number} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param playlist {module:model/PlaylistEntity} 
     * @param file {module:model/FileEntity} 
     */
    constructor(id, position, duration, createdAt, updatedAt, playlist, file) { 
        
        PlaylistItemEntity.initialize(this, id, position, duration, createdAt, updatedAt, playlist, file);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, position, duration, createdAt, updatedAt, playlist, file) { 
        obj['id'] = id;
        obj['position'] = position;
        obj['duration'] = duration;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['playlist'] = playlist;
        obj['file'] = file;
    }

    /**
     * Constructs a <code>PlaylistItemEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaylistItemEntity} obj Optional instance to populate.
     * @return {module:model/PlaylistItemEntity} The populated <code>PlaylistItemEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistItemEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('playlist')) {
                obj['playlist'] = PlaylistEntity.constructFromObject(data['playlist']);
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = FileEntity.constructFromObject(data['file']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlaylistItemEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlaylistItemEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlaylistItemEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `playlist`
        if (data['playlist']) { // data not null
          PlaylistEntity.validateJSON(data['playlist']);
        }
        // validate the optional field `file`
        if (data['file']) { // data not null
          FileEntity.validateJSON(data['file']);
        }

        return true;
    }


}

PlaylistItemEntity.RequiredProperties = ["id", "position", "duration", "createdAt", "updatedAt", "playlist", "file"];

/**
 * @member {Number} id
 */
PlaylistItemEntity.prototype['id'] = undefined;

/**
 * @member {Number} position
 */
PlaylistItemEntity.prototype['position'] = undefined;

/**
 * @member {Number} duration
 */
PlaylistItemEntity.prototype['duration'] = undefined;

/**
 * @member {Date} createdAt
 */
PlaylistItemEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
PlaylistItemEntity.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/PlaylistEntity} playlist
 */
PlaylistItemEntity.prototype['playlist'] = undefined;

/**
 * @member {module:model/FileEntity} file
 */
PlaylistItemEntity.prototype['file'] = undefined;






export default PlaylistItemEntity;

