/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlaylistItemEntity from './PlaylistItemEntity';

/**
 * The PlaylistEntity model module.
 * @module model/PlaylistEntity
 * @version 1.0
 */
class PlaylistEntity {
    /**
     * Constructs a new <code>PlaylistEntity</code>.
     * @alias module:model/PlaylistEntity
     * @param id {Number} 
     * @param name {String} 
     * @param description {Object} 
     * @param revision {Number} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param items {Array.<module:model/PlaylistItemEntity>} 
     * @param screenPlaylists {Array.<Object>} 
     * @param screenStates {Array.<Object>} 
     */
    constructor(id, name, description, revision, createdAt, updatedAt, items, screenPlaylists, screenStates) { 
        
        PlaylistEntity.initialize(this, id, name, description, revision, createdAt, updatedAt, items, screenPlaylists, screenStates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, description, revision, createdAt, updatedAt, items, screenPlaylists, screenStates) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['description'] = description;
        obj['revision'] = revision;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
        obj['items'] = items;
        obj['screenPlaylists'] = screenPlaylists;
        obj['screenStates'] = screenStates;
    }

    /**
     * Constructs a <code>PlaylistEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaylistEntity} obj Optional instance to populate.
     * @return {module:model/PlaylistEntity} The populated <code>PlaylistEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], Object);
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PlaylistItemEntity]);
            }
            if (data.hasOwnProperty('screenPlaylists')) {
                obj['screenPlaylists'] = ApiClient.convertToType(data['screenPlaylists'], [Object]);
            }
            if (data.hasOwnProperty('screenStates')) {
                obj['screenStates'] = ApiClient.convertToType(data['screenStates'], [Object]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlaylistEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlaylistEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlaylistEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PlaylistItemEntity.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['screenPlaylists'])) {
            throw new Error("Expected the field `screenPlaylists` to be an array in the JSON data but got " + data['screenPlaylists']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['screenStates'])) {
            throw new Error("Expected the field `screenStates` to be an array in the JSON data but got " + data['screenStates']);
        }

        return true;
    }


}

PlaylistEntity.RequiredProperties = ["id", "name", "description", "revision", "createdAt", "updatedAt", "items", "screenPlaylists", "screenStates"];

/**
 * @member {Number} id
 */
PlaylistEntity.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PlaylistEntity.prototype['name'] = undefined;

/**
 * @member {Object} description
 */
PlaylistEntity.prototype['description'] = undefined;

/**
 * @member {Number} revision
 */
PlaylistEntity.prototype['revision'] = undefined;

/**
 * @member {Date} createdAt
 */
PlaylistEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
PlaylistEntity.prototype['updatedAt'] = undefined;

/**
 * @member {Array.<module:model/PlaylistItemEntity>} items
 */
PlaylistEntity.prototype['items'] = undefined;

/**
 * @member {Array.<Object>} screenPlaylists
 */
PlaylistEntity.prototype['screenPlaylists'] = undefined;

/**
 * @member {Array.<Object>} screenStates
 */
PlaylistEntity.prototype['screenStates'] = undefined;






export default PlaylistEntity;

