/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlaylistEntity model module.
 * @module model/PlaylistEntity
 * @version 1.0
 */
class PlaylistEntity {
    /**
     * Constructs a new <code>PlaylistEntity</code>.
     * @alias module:model/PlaylistEntity
     * @param id {Number} 
     * @param name {String} 
     * @param description {Object} 
     * @param revision {Number} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, name, description, revision, createdAt, updatedAt) { 
        
        PlaylistEntity.initialize(this, id, name, description, revision, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, description, revision, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['description'] = description;
        obj['revision'] = revision;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>PlaylistEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlaylistEntity} obj Optional instance to populate.
     * @return {module:model/PlaylistEntity} The populated <code>PlaylistEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], Object);
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlaylistEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlaylistEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PlaylistEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

PlaylistEntity.RequiredProperties = ["id", "name", "description", "revision", "createdAt", "updatedAt"];

/**
 * @member {Number} id
 */
PlaylistEntity.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PlaylistEntity.prototype['name'] = undefined;

/**
 * @member {Object} description
 */
PlaylistEntity.prototype['description'] = undefined;

/**
 * @member {Number} revision
 */
PlaylistEntity.prototype['revision'] = undefined;

/**
 * @member {Date} createdAt
 */
PlaylistEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
PlaylistEntity.prototype['updatedAt'] = undefined;






export default PlaylistEntity;

