/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReorderPlaylistItemsDto model module.
 * @module model/ReorderPlaylistItemsDto
 * @version 1.0
 */
class ReorderPlaylistItemsDto {
    /**
     * Constructs a new <code>ReorderPlaylistItemsDto</code>.
     * @alias module:model/ReorderPlaylistItemsDto
     * @param itemIds {Array.<Number>} 
     */
    constructor(itemIds) { 
        
        ReorderPlaylistItemsDto.initialize(this, itemIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, itemIds) { 
        obj['itemIds'] = itemIds;
    }

    /**
     * Constructs a <code>ReorderPlaylistItemsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReorderPlaylistItemsDto} obj Optional instance to populate.
     * @return {module:model/ReorderPlaylistItemsDto} The populated <code>ReorderPlaylistItemsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReorderPlaylistItemsDto();

            if (data.hasOwnProperty('itemIds')) {
                obj['itemIds'] = ApiClient.convertToType(data['itemIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReorderPlaylistItemsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReorderPlaylistItemsDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReorderPlaylistItemsDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['itemIds'])) {
            throw new Error("Expected the field `itemIds` to be an array in the JSON data but got " + data['itemIds']);
        }

        return true;
    }


}

ReorderPlaylistItemsDto.RequiredProperties = ["itemIds"];

/**
 * @member {Array.<Number>} itemIds
 */
ReorderPlaylistItemsDto.prototype['itemIds'] = undefined;






export default ReorderPlaylistItemsDto;

