/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScreenPlaylistEntity model module.
 * @module model/ScreenPlaylistEntity
 * @version 1.0
 */
class ScreenPlaylistEntity {
    /**
     * Constructs a new <code>ScreenPlaylistEntity</code>.
     * @alias module:model/ScreenPlaylistEntity
     * @param id {Number} Unique identifier for the screen-playlist association
     * @param screenId {Number} Identifier for the associated screen
     * @param playlistId {Number} Identifier for the associated playlist
     * @param priority {Number} Priority of the screen-playlist association
     * @param activeFrom {Object} Start date and time when the playlist becomes active on the screen
     * @param activeTo {Object} End date and time when the playlist is no longer active on the screen
     * @param revision {Number} Revision number for the screen-playlist association
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, screenId, playlistId, priority, activeFrom, activeTo, revision, createdAt, updatedAt) { 
        
        ScreenPlaylistEntity.initialize(this, id, screenId, playlistId, priority, activeFrom, activeTo, revision, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, screenId, playlistId, priority, activeFrom, activeTo, revision, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['screenId'] = screenId;
        obj['playlistId'] = playlistId;
        obj['priority'] = priority;
        obj['activeFrom'] = activeFrom;
        obj['activeTo'] = activeTo;
        obj['revision'] = revision;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>ScreenPlaylistEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScreenPlaylistEntity} obj Optional instance to populate.
     * @return {module:model/ScreenPlaylistEntity} The populated <code>ScreenPlaylistEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScreenPlaylistEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('screenId')) {
                obj['screenId'] = ApiClient.convertToType(data['screenId'], 'Number');
            }
            if (data.hasOwnProperty('playlistId')) {
                obj['playlistId'] = ApiClient.convertToType(data['playlistId'], 'Number');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('activeFrom')) {
                obj['activeFrom'] = ApiClient.convertToType(data['activeFrom'], Object);
            }
            if (data.hasOwnProperty('activeTo')) {
                obj['activeTo'] = ApiClient.convertToType(data['activeTo'], Object);
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScreenPlaylistEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScreenPlaylistEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScreenPlaylistEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ScreenPlaylistEntity.RequiredProperties = ["id", "screenId", "playlistId", "priority", "activeFrom", "activeTo", "revision", "createdAt", "updatedAt"];

/**
 * Unique identifier for the screen-playlist association
 * @member {Number} id
 */
ScreenPlaylistEntity.prototype['id'] = undefined;

/**
 * Identifier for the associated screen
 * @member {Number} screenId
 */
ScreenPlaylistEntity.prototype['screenId'] = undefined;

/**
 * Identifier for the associated playlist
 * @member {Number} playlistId
 */
ScreenPlaylistEntity.prototype['playlistId'] = undefined;

/**
 * Priority of the screen-playlist association
 * @member {Number} priority
 */
ScreenPlaylistEntity.prototype['priority'] = undefined;

/**
 * Start date and time when the playlist becomes active on the screen
 * @member {Object} activeFrom
 */
ScreenPlaylistEntity.prototype['activeFrom'] = undefined;

/**
 * End date and time when the playlist is no longer active on the screen
 * @member {Object} activeTo
 */
ScreenPlaylistEntity.prototype['activeTo'] = undefined;

/**
 * Revision number for the screen-playlist association
 * @member {Number} revision
 */
ScreenPlaylistEntity.prototype['revision'] = undefined;

/**
 * @member {Date} createdAt
 */
ScreenPlaylistEntity.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ScreenPlaylistEntity.prototype['updatedAt'] = undefined;






export default ScreenPlaylistEntity;

