/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileEntity from './FileEntity';
import ScreenLogEntity from './ScreenLogEntity';
import ScreenPlaylistEntity from './ScreenPlaylistEntity';
import ScreenStateEntity from './ScreenStateEntity';

/**
 * The ScreenEntity model module.
 * @module model/ScreenEntity
 * @version 1.0
 */
class ScreenEntity {
    /**
     * Constructs a new <code>ScreenEntity</code>.
     * @alias module:model/ScreenEntity
     * @param id {Number} 
     * @param name {String} 
     * @param location {String} 
     * @param apiKey {String} 
     * @param fallbackFileId {Number} ID pliku fallback
     * @param playerUrl {String} 
     * @param lastSeen {Date} 
     * @param isOnline {Boolean} 
     * @param createdAt {Date} 
     * @param screenPlaylists {Array.<module:model/ScreenPlaylistEntity>} 
     * @param screenLogs {Array.<module:model/ScreenLogEntity>} 
     * @param state {module:model/ScreenStateEntity} 
     * @param fallbackFile {module:model/FileEntity} 
     */
    constructor(id, name, location, apiKey, fallbackFileId, playerUrl, lastSeen, isOnline, createdAt, screenPlaylists, screenLogs, state, fallbackFile) { 
        
        ScreenEntity.initialize(this, id, name, location, apiKey, fallbackFileId, playerUrl, lastSeen, isOnline, createdAt, screenPlaylists, screenLogs, state, fallbackFile);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, location, apiKey, fallbackFileId, playerUrl, lastSeen, isOnline, createdAt, screenPlaylists, screenLogs, state, fallbackFile) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['location'] = location;
        obj['apiKey'] = apiKey;
        obj['fallbackFileId'] = fallbackFileId;
        obj['playerUrl'] = playerUrl;
        obj['lastSeen'] = lastSeen;
        obj['isOnline'] = isOnline;
        obj['createdAt'] = createdAt;
        obj['screenPlaylists'] = screenPlaylists;
        obj['screenLogs'] = screenLogs;
        obj['state'] = state;
        obj['fallbackFile'] = fallbackFile;
    }

    /**
     * Constructs a <code>ScreenEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScreenEntity} obj Optional instance to populate.
     * @return {module:model/ScreenEntity} The populated <code>ScreenEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScreenEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
            }
            if (data.hasOwnProperty('fallbackFileId')) {
                obj['fallbackFileId'] = ApiClient.convertToType(data['fallbackFileId'], 'Number');
            }
            if (data.hasOwnProperty('playerUrl')) {
                obj['playerUrl'] = ApiClient.convertToType(data['playerUrl'], 'String');
            }
            if (data.hasOwnProperty('lastSeen')) {
                obj['lastSeen'] = ApiClient.convertToType(data['lastSeen'], 'Date');
            }
            if (data.hasOwnProperty('isOnline')) {
                obj['isOnline'] = ApiClient.convertToType(data['isOnline'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('screenPlaylists')) {
                obj['screenPlaylists'] = ApiClient.convertToType(data['screenPlaylists'], [ScreenPlaylistEntity]);
            }
            if (data.hasOwnProperty('screenLogs')) {
                obj['screenLogs'] = ApiClient.convertToType(data['screenLogs'], [ScreenLogEntity]);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], ScreenStateEntity);
            }
            if (data.hasOwnProperty('fallbackFile')) {
                obj['fallbackFile'] = FileEntity.constructFromObject(data['fallbackFile']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScreenEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScreenEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScreenEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }
        // ensure the json data is a string
        if (data['apiKey'] && !(typeof data['apiKey'] === 'string' || data['apiKey'] instanceof String)) {
            throw new Error("Expected the field `apiKey` to be a primitive type in the JSON string but got " + data['apiKey']);
        }
        // ensure the json data is a string
        if (data['playerUrl'] && !(typeof data['playerUrl'] === 'string' || data['playerUrl'] instanceof String)) {
            throw new Error("Expected the field `playerUrl` to be a primitive type in the JSON string but got " + data['playerUrl']);
        }
        if (data['screenPlaylists']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['screenPlaylists'])) {
                throw new Error("Expected the field `screenPlaylists` to be an array in the JSON data but got " + data['screenPlaylists']);
            }
            // validate the optional field `screenPlaylists` (array)
            for (const item of data['screenPlaylists']) {
                ScreenPlaylistEntity.validateJSON(item);
            };
        }
        if (data['screenLogs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['screenLogs'])) {
                throw new Error("Expected the field `screenLogs` to be an array in the JSON data but got " + data['screenLogs']);
            }
            // validate the optional field `screenLogs` (array)
            for (const item of data['screenLogs']) {
                ScreenLogEntity.validateJSON(item);
            };
        }
        // validate the optional field `state`
        if (data['state']) { // data not null
          ScreenStateEntity.validateJSON(data['state']);
        }
        // validate the optional field `fallbackFile`
        if (data['fallbackFile']) { // data not null
          FileEntity.validateJSON(data['fallbackFile']);
        }

        return true;
    }


}

ScreenEntity.RequiredProperties = ["id", "name", "location", "apiKey", "fallbackFileId", "playerUrl", "lastSeen", "isOnline", "createdAt", "screenPlaylists", "screenLogs", "state", "fallbackFile"];

/**
 * @member {Number} id
 */
ScreenEntity.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ScreenEntity.prototype['name'] = undefined;

/**
 * @member {String} location
 */
ScreenEntity.prototype['location'] = undefined;

/**
 * @member {String} apiKey
 */
ScreenEntity.prototype['apiKey'] = undefined;

/**
 * ID pliku fallback
 * @member {Number} fallbackFileId
 */
ScreenEntity.prototype['fallbackFileId'] = undefined;

/**
 * @member {String} playerUrl
 */
ScreenEntity.prototype['playerUrl'] = undefined;

/**
 * @member {Date} lastSeen
 */
ScreenEntity.prototype['lastSeen'] = undefined;

/**
 * @member {Boolean} isOnline
 */
ScreenEntity.prototype['isOnline'] = undefined;

/**
 * @member {Date} createdAt
 */
ScreenEntity.prototype['createdAt'] = undefined;

/**
 * @member {Array.<module:model/ScreenPlaylistEntity>} screenPlaylists
 */
ScreenEntity.prototype['screenPlaylists'] = undefined;

/**
 * @member {Array.<module:model/ScreenLogEntity>} screenLogs
 */
ScreenEntity.prototype['screenLogs'] = undefined;

/**
 * @member {module:model/ScreenStateEntity} state
 */
ScreenEntity.prototype['state'] = undefined;

/**
 * @member {module:model/FileEntity} fallbackFile
 */
ScreenEntity.prototype['fallbackFile'] = undefined;






export default ScreenEntity;

