/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScreenPlaylistEntity from './ScreenPlaylistEntity';

/**
 * The ScreenEntity model module.
 * @module model/ScreenEntity
 * @version 1.0
 */
class ScreenEntity {
    /**
     * Constructs a new <code>ScreenEntity</code>.
     * @alias module:model/ScreenEntity
     * @param id {Number} 
     * @param name {String} 
     * @param location {Object} 
     * @param apiKey {Object} 
     * @param fallbackFileId {Number} ID pliku fallback
     * @param createdAt {Date} 
     * @param screenPlaylists {Array.<module:model/ScreenPlaylistEntity>} 
     * @param logs {Array.<Object>} 
     * @param state {Object} 
     */
    constructor(id, name, location, apiKey, fallbackFileId, createdAt, screenPlaylists, logs, state) { 
        
        ScreenEntity.initialize(this, id, name, location, apiKey, fallbackFileId, createdAt, screenPlaylists, logs, state);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, location, apiKey, fallbackFileId, createdAt, screenPlaylists, logs, state) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['location'] = location;
        obj['apiKey'] = apiKey;
        obj['fallbackFileId'] = fallbackFileId;
        obj['createdAt'] = createdAt;
        obj['screenPlaylists'] = screenPlaylists;
        obj['logs'] = logs;
        obj['state'] = state;
    }

    /**
     * Constructs a <code>ScreenEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScreenEntity} obj Optional instance to populate.
     * @return {module:model/ScreenEntity} The populated <code>ScreenEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScreenEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], Object);
            }
            if (data.hasOwnProperty('apiKey')) {
                obj['apiKey'] = ApiClient.convertToType(data['apiKey'], Object);
            }
            if (data.hasOwnProperty('fallbackFileId')) {
                obj['fallbackFileId'] = ApiClient.convertToType(data['fallbackFileId'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('screenPlaylists')) {
                obj['screenPlaylists'] = ApiClient.convertToType(data['screenPlaylists'], [ScreenPlaylistEntity]);
            }
            if (data.hasOwnProperty('logs')) {
                obj['logs'] = ApiClient.convertToType(data['logs'], [Object]);
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScreenEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScreenEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScreenEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['screenPlaylists']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['screenPlaylists'])) {
                throw new Error("Expected the field `screenPlaylists` to be an array in the JSON data but got " + data['screenPlaylists']);
            }
            // validate the optional field `screenPlaylists` (array)
            for (const item of data['screenPlaylists']) {
                ScreenPlaylistEntity.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['logs'])) {
            throw new Error("Expected the field `logs` to be an array in the JSON data but got " + data['logs']);
        }

        return true;
    }


}

ScreenEntity.RequiredProperties = ["id", "name", "location", "apiKey", "fallbackFileId", "createdAt", "screenPlaylists", "logs", "state"];

/**
 * @member {Number} id
 */
ScreenEntity.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ScreenEntity.prototype['name'] = undefined;

/**
 * @member {Object} location
 */
ScreenEntity.prototype['location'] = undefined;

/**
 * @member {Object} apiKey
 */
ScreenEntity.prototype['apiKey'] = undefined;

/**
 * ID pliku fallback
 * @member {Number} fallbackFileId
 */
ScreenEntity.prototype['fallbackFileId'] = undefined;

/**
 * @member {Date} createdAt
 */
ScreenEntity.prototype['createdAt'] = undefined;

/**
 * @member {Array.<module:model/ScreenPlaylistEntity>} screenPlaylists
 */
ScreenEntity.prototype['screenPlaylists'] = undefined;

/**
 * @member {Array.<Object>} logs
 */
ScreenEntity.prototype['logs'] = undefined;

/**
 * @member {Object} state
 */
ScreenEntity.prototype['state'] = undefined;






export default ScreenEntity;

