/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScreenLogEntity model module.
 * @module model/ScreenLogEntity
 * @version 1.0
 */
class ScreenLogEntity {
    /**
     * Constructs a new <code>ScreenLogEntity</code>.
     * @alias module:model/ScreenLogEntity
     * @param id {Number} 
     * @param screenId {Number} 
     * @param message {String} 
     * @param level {String} 
     * @param createdAt {Date} 
     */
    constructor(id, screenId, message, level, createdAt) { 
        
        ScreenLogEntity.initialize(this, id, screenId, message, level, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, screenId, message, level, createdAt) { 
        obj['id'] = id;
        obj['screenId'] = screenId;
        obj['message'] = message;
        obj['level'] = level;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>ScreenLogEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScreenLogEntity} obj Optional instance to populate.
     * @return {module:model/ScreenLogEntity} The populated <code>ScreenLogEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScreenLogEntity();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('screenId')) {
                obj['screenId'] = ApiClient.convertToType(data['screenId'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScreenLogEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScreenLogEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScreenLogEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['level'] && !(typeof data['level'] === 'string' || data['level'] instanceof String)) {
            throw new Error("Expected the field `level` to be a primitive type in the JSON string but got " + data['level']);
        }

        return true;
    }


}

ScreenLogEntity.RequiredProperties = ["id", "screenId", "message", "level", "createdAt"];

/**
 * @member {Number} id
 */
ScreenLogEntity.prototype['id'] = undefined;

/**
 * @member {Number} screenId
 */
ScreenLogEntity.prototype['screenId'] = undefined;

/**
 * @member {String} message
 */
ScreenLogEntity.prototype['message'] = undefined;

/**
 * @member {String} level
 */
ScreenLogEntity.prototype['level'] = undefined;

/**
 * @member {Date} createdAt
 */
ScreenLogEntity.prototype['createdAt'] = undefined;






export default ScreenLogEntity;

