/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlaylistEntity from './PlaylistEntity';
import ScreenEntity from './ScreenEntity';

/**
 * The ScreenStateEntity model module.
 * @module model/ScreenStateEntity
 * @version 1.0
 */
class ScreenStateEntity {
    /**
     * Constructs a new <code>ScreenStateEntity</code>.
     * @alias module:model/ScreenStateEntity
     * @param screenId {Number} 
     * @param lastSync {Date} 
     * @param lastPlaylistHash {String} 
     * @param currentIndex {Number} 
     * @param visible {Boolean} 
     * @param updatedAt {Date} 
     * @param screen {module:model/ScreenEntity} 
     * @param currentPlaylist {module:model/PlaylistEntity} 
     * @param currentPlaylistId {Number} 
     */
    constructor(screenId, lastSync, lastPlaylistHash, currentIndex, visible, updatedAt, screen, currentPlaylist, currentPlaylistId) { 
        
        ScreenStateEntity.initialize(this, screenId, lastSync, lastPlaylistHash, currentIndex, visible, updatedAt, screen, currentPlaylist, currentPlaylistId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, screenId, lastSync, lastPlaylistHash, currentIndex, visible, updatedAt, screen, currentPlaylist, currentPlaylistId) { 
        obj['screenId'] = screenId;
        obj['lastSync'] = lastSync;
        obj['lastPlaylistHash'] = lastPlaylistHash;
        obj['currentIndex'] = currentIndex;
        obj['visible'] = visible;
        obj['updatedAt'] = updatedAt;
        obj['screen'] = screen;
        obj['currentPlaylist'] = currentPlaylist;
        obj['currentPlaylistId'] = currentPlaylistId;
    }

    /**
     * Constructs a <code>ScreenStateEntity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScreenStateEntity} obj Optional instance to populate.
     * @return {module:model/ScreenStateEntity} The populated <code>ScreenStateEntity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScreenStateEntity();

            if (data.hasOwnProperty('screenId')) {
                obj['screenId'] = ApiClient.convertToType(data['screenId'], 'Number');
            }
            if (data.hasOwnProperty('lastSync')) {
                obj['lastSync'] = ApiClient.convertToType(data['lastSync'], 'Date');
            }
            if (data.hasOwnProperty('lastPlaylistHash')) {
                obj['lastPlaylistHash'] = ApiClient.convertToType(data['lastPlaylistHash'], 'String');
            }
            if (data.hasOwnProperty('currentIndex')) {
                obj['currentIndex'] = ApiClient.convertToType(data['currentIndex'], 'Number');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
            if (data.hasOwnProperty('screen')) {
                obj['screen'] = ScreenEntity.constructFromObject(data['screen']);
            }
            if (data.hasOwnProperty('currentPlaylist')) {
                obj['currentPlaylist'] = ApiClient.convertToType(data['currentPlaylist'], PlaylistEntity);
            }
            if (data.hasOwnProperty('currentPlaylistId')) {
                obj['currentPlaylistId'] = ApiClient.convertToType(data['currentPlaylistId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ScreenStateEntity</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ScreenStateEntity</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ScreenStateEntity.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['lastPlaylistHash'] && !(typeof data['lastPlaylistHash'] === 'string' || data['lastPlaylistHash'] instanceof String)) {
            throw new Error("Expected the field `lastPlaylistHash` to be a primitive type in the JSON string but got " + data['lastPlaylistHash']);
        }
        // validate the optional field `screen`
        if (data['screen']) { // data not null
          ScreenEntity.validateJSON(data['screen']);
        }
        // validate the optional field `currentPlaylist`
        if (data['currentPlaylist']) { // data not null
          PlaylistEntity.validateJSON(data['currentPlaylist']);
        }

        return true;
    }


}

ScreenStateEntity.RequiredProperties = ["screenId", "lastSync", "lastPlaylistHash", "currentIndex", "visible", "updatedAt", "screen", "currentPlaylist", "currentPlaylistId"];

/**
 * @member {Number} screenId
 */
ScreenStateEntity.prototype['screenId'] = undefined;

/**
 * @member {Date} lastSync
 */
ScreenStateEntity.prototype['lastSync'] = undefined;

/**
 * @member {String} lastPlaylistHash
 */
ScreenStateEntity.prototype['lastPlaylistHash'] = undefined;

/**
 * @member {Number} currentIndex
 */
ScreenStateEntity.prototype['currentIndex'] = undefined;

/**
 * @member {Boolean} visible
 */
ScreenStateEntity.prototype['visible'] = undefined;

/**
 * @member {Date} updatedAt
 */
ScreenStateEntity.prototype['updatedAt'] = undefined;

/**
 * @member {module:model/ScreenEntity} screen
 */
ScreenStateEntity.prototype['screen'] = undefined;

/**
 * @member {module:model/PlaylistEntity} currentPlaylist
 */
ScreenStateEntity.prototype['currentPlaylist'] = undefined;

/**
 * @member {Number} currentPlaylistId
 */
ScreenStateEntity.prototype['currentPlaylistId'] = undefined;






export default ScreenStateEntity;

