/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateScreenStateDto model module.
 * @module model/UpdateScreenStateDto
 * @version 1.0
 */
class UpdateScreenStateDto {
    /**
     * Constructs a new <code>UpdateScreenStateDto</code>.
     * @alias module:model/UpdateScreenStateDto
     * @param currentPlaylistId {Number} 
     * @param currentIndex {Number} 
     * @param visible {Boolean} 
     */
    constructor(currentPlaylistId, currentIndex, visible) { 
        
        UpdateScreenStateDto.initialize(this, currentPlaylistId, currentIndex, visible);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentPlaylistId, currentIndex, visible) { 
        obj['currentPlaylistId'] = currentPlaylistId;
        obj['currentIndex'] = currentIndex;
        obj['visible'] = visible;
    }

    /**
     * Constructs a <code>UpdateScreenStateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateScreenStateDto} obj Optional instance to populate.
     * @return {module:model/UpdateScreenStateDto} The populated <code>UpdateScreenStateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateScreenStateDto();

            if (data.hasOwnProperty('currentPlaylistId')) {
                obj['currentPlaylistId'] = ApiClient.convertToType(data['currentPlaylistId'], 'Number');
            }
            if (data.hasOwnProperty('currentIndex')) {
                obj['currentIndex'] = ApiClient.convertToType(data['currentIndex'], 'Number');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateScreenStateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateScreenStateDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateScreenStateDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UpdateScreenStateDto.RequiredProperties = ["currentPlaylistId", "currentIndex", "visible"];

/**
 * @member {Number} currentPlaylistId
 */
UpdateScreenStateDto.prototype['currentPlaylistId'] = undefined;

/**
 * @member {Number} currentIndex
 */
UpdateScreenStateDto.prototype['currentIndex'] = undefined;

/**
 * @member {Boolean} visible
 */
UpdateScreenStateDto.prototype['visible'] = undefined;






export default UpdateScreenStateDto;

