/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdatePlaylistItemDto from './UpdatePlaylistItemDto';

/**
 * The UpdatePlaylistDto model module.
 * @module model/UpdatePlaylistDto
 * @version 1.0
 */
class UpdatePlaylistDto {
    /**
     * Constructs a new <code>UpdatePlaylistDto</code>.
     * @alias module:model/UpdatePlaylistDto
     */
    constructor() { 
        
        UpdatePlaylistDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdatePlaylistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePlaylistDto} obj Optional instance to populate.
     * @return {module:model/UpdatePlaylistDto} The populated <code>UpdatePlaylistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePlaylistDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('repeatMode')) {
                obj['repeatMode'] = ApiClient.convertToType(data['repeatMode'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [UpdatePlaylistItemDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdatePlaylistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdatePlaylistDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['repeatMode'] && !(typeof data['repeatMode'] === 'string' || data['repeatMode'] instanceof String)) {
            throw new Error("Expected the field `repeatMode` to be a primitive type in the JSON string but got " + data['repeatMode']);
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                UpdatePlaylistItemDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} name
 */
UpdatePlaylistDto.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UpdatePlaylistDto.prototype['description'] = undefined;

/**
 * @member {module:model/UpdatePlaylistDto.RepeatModeEnum} repeatMode
 */
UpdatePlaylistDto.prototype['repeatMode'] = undefined;

/**
 * @member {Array.<module:model/UpdatePlaylistItemDto>} items
 */
UpdatePlaylistDto.prototype['items'] = undefined;





/**
 * Allowed values for the <code>repeatMode</code> property.
 * @enum {String}
 * @readonly
 */
UpdatePlaylistDto['RepeatModeEnum'] = {

    /**
     * value: "LOOP"
     * @const
     */
    "LOOP": "LOOP",

    /**
     * value: "FALLBACK"
     * @const
     */
    "FALLBACK": "FALLBACK"
};



export default UpdatePlaylistDto;

