/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateScreenDto model module.
 * @module model/UpdateScreenDto
 * @version 1.0
 */
class UpdateScreenDto {
    /**
     * Constructs a new <code>UpdateScreenDto</code>.
     * @alias module:model/UpdateScreenDto
     */
    constructor() { 
        
        UpdateScreenDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateScreenDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateScreenDto} obj Optional instance to populate.
     * @return {module:model/UpdateScreenDto} The populated <code>UpdateScreenDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateScreenDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('fallbackFileId')) {
                obj['fallbackFileId'] = ApiClient.convertToType(data['fallbackFileId'], 'Number');
            }
            if (data.hasOwnProperty('playerUrl')) {
                obj['playerUrl'] = ApiClient.convertToType(data['playerUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateScreenDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateScreenDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }
        // ensure the json data is a string
        if (data['playerUrl'] && !(typeof data['playerUrl'] === 'string' || data['playerUrl'] instanceof String)) {
            throw new Error("Expected the field `playerUrl` to be a primitive type in the JSON string but got " + data['playerUrl']);
        }

        return true;
    }


}



/**
 * Nazwa ekranu
 * @member {String} name
 */
UpdateScreenDto.prototype['name'] = undefined;

/**
 * Lokalizacja ekranu
 * @member {String} location
 */
UpdateScreenDto.prototype['location'] = undefined;

/**
 * ID pliku używanego jako fallback
 * @member {Number} fallbackFileId
 */
UpdateScreenDto.prototype['fallbackFileId'] = undefined;

/**
 * Adres aplikacji Player dla tego ekranu
 * @member {String} playerUrl
 */
UpdateScreenDto.prototype['playerUrl'] = undefined;






export default UpdateScreenDto;

