/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdatePlaylistItemDto model module.
 * @module model/UpdatePlaylistItemDto
 * @version 1.0
 */
class UpdatePlaylistItemDto {
    /**
     * Constructs a new <code>UpdatePlaylistItemDto</code>.
     * @alias module:model/UpdatePlaylistItemDto
     * @param id {Number} 
     * @param position {Number} 
     * @param duration {Number} 
     */
    constructor(id, position, duration) { 
        
        UpdatePlaylistItemDto.initialize(this, id, position, duration);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, position, duration) { 
        obj['id'] = id;
        obj['position'] = position;
        obj['duration'] = duration;
    }

    /**
     * Constructs a <code>UpdatePlaylistItemDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePlaylistItemDto} obj Optional instance to populate.
     * @return {module:model/UpdatePlaylistItemDto} The populated <code>UpdatePlaylistItemDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePlaylistItemDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('videoLoops')) {
                obj['videoLoops'] = ApiClient.convertToType(data['videoLoops'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdatePlaylistItemDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdatePlaylistItemDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdatePlaylistItemDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UpdatePlaylistItemDto.RequiredProperties = ["id", "position", "duration"];

/**
 * @member {Number} id
 */
UpdatePlaylistItemDto.prototype['id'] = undefined;

/**
 * @member {Number} position
 */
UpdatePlaylistItemDto.prototype['position'] = undefined;

/**
 * @member {Number} duration
 */
UpdatePlaylistItemDto.prototype['duration'] = undefined;

/**
 * @member {Number} videoLoops
 */
UpdatePlaylistItemDto.prototype['videoLoops'] = undefined;






export default UpdatePlaylistItemDto;

