/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateScreenHeartbeatDto model module.
 * @module model/UpdateScreenHeartbeatDto
 * @version 1.0
 */
class UpdateScreenHeartbeatDto {
    /**
     * Constructs a new <code>UpdateScreenHeartbeatDto</code>.
     * @alias module:model/UpdateScreenHeartbeatDto
     * @param playerUrl {String} 
     * @param visible {Boolean} 
     */
    constructor(playerUrl, visible) { 
        
        UpdateScreenHeartbeatDto.initialize(this, playerUrl, visible);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerUrl, visible) { 
        obj['playerUrl'] = playerUrl;
        obj['visible'] = visible;
    }

    /**
     * Constructs a <code>UpdateScreenHeartbeatDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateScreenHeartbeatDto} obj Optional instance to populate.
     * @return {module:model/UpdateScreenHeartbeatDto} The populated <code>UpdateScreenHeartbeatDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateScreenHeartbeatDto();

            if (data.hasOwnProperty('playerUrl')) {
                obj['playerUrl'] = ApiClient.convertToType(data['playerUrl'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateScreenHeartbeatDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateScreenHeartbeatDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateScreenHeartbeatDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['playerUrl'] && !(typeof data['playerUrl'] === 'string' || data['playerUrl'] instanceof String)) {
            throw new Error("Expected the field `playerUrl` to be a primitive type in the JSON string but got " + data['playerUrl']);
        }

        return true;
    }


}

UpdateScreenHeartbeatDto.RequiredProperties = ["playerUrl", "visible"];

/**
 * @member {String} playerUrl
 */
UpdateScreenHeartbeatDto.prototype['playerUrl'] = undefined;

/**
 * @member {Boolean} visible
 */
UpdateScreenHeartbeatDto.prototype['visible'] = undefined;






export default UpdateScreenHeartbeatDto;

