/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateScreenPlaylistDto model module.
 * @module model/UpdateScreenPlaylistDto
 * @version 1.0
 */
class UpdateScreenPlaylistDto {
    /**
     * Constructs a new <code>UpdateScreenPlaylistDto</code>.
     * @alias module:model/UpdateScreenPlaylistDto
     */
    constructor() { 
        
        UpdateScreenPlaylistDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateScreenPlaylistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateScreenPlaylistDto} obj Optional instance to populate.
     * @return {module:model/UpdateScreenPlaylistDto} The populated <code>UpdateScreenPlaylistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateScreenPlaylistDto();

            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('activeFrom')) {
                obj['activeFrom'] = ApiClient.convertToType(data['activeFrom'], 'String');
            }
            if (data.hasOwnProperty('activeTo')) {
                obj['activeTo'] = ApiClient.convertToType(data['activeTo'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateScreenPlaylistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateScreenPlaylistDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['activeFrom'] && !(typeof data['activeFrom'] === 'string' || data['activeFrom'] instanceof String)) {
            throw new Error("Expected the field `activeFrom` to be a primitive type in the JSON string but got " + data['activeFrom']);
        }
        // ensure the json data is a string
        if (data['activeTo'] && !(typeof data['activeTo'] === 'string' || data['activeTo'] instanceof String)) {
            throw new Error("Expected the field `activeTo` to be a primitive type in the JSON string but got " + data['activeTo']);
        }

        return true;
    }


}



/**
 * @member {Number} priority
 */
UpdateScreenPlaylistDto.prototype['priority'] = undefined;

/**
 * @member {String} activeFrom
 */
UpdateScreenPlaylistDto.prototype['activeFrom'] = undefined;

/**
 * @member {String} activeTo
 */
UpdateScreenPlaylistDto.prototype['activeTo'] = undefined;






export default UpdateScreenPlaylistDto;

