/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.FilesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FilesApi', function() {
    describe('filesControllerCheckIfUsed', function() {
      it('should call filesControllerCheckIfUsed successfully', function(done) {
        //uncomment below and update the code to test filesControllerCheckIfUsed
        //instance.filesControllerCheckIfUsed(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerCreate', function() {
      it('should call filesControllerCreate successfully', function(done) {
        //uncomment below and update the code to test filesControllerCreate
        //instance.filesControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerDelete', function() {
      it('should call filesControllerDelete successfully', function(done) {
        //uncomment below and update the code to test filesControllerDelete
        //instance.filesControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerFindAll', function() {
      it('should call filesControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test filesControllerFindAll
        //instance.filesControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerFindById', function() {
      it('should call filesControllerFindById successfully', function(done) {
        //uncomment below and update the code to test filesControllerFindById
        //instance.filesControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerGetAllImages', function() {
      it('should call filesControllerGetAllImages successfully', function(done) {
        //uncomment below and update the code to test filesControllerGetAllImages
        //instance.filesControllerGetAllImages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerGetAllVideos', function() {
      it('should call filesControllerGetAllVideos successfully', function(done) {
        //uncomment below and update the code to test filesControllerGetAllVideos
        //instance.filesControllerGetAllVideos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('filesControllerUpdate', function() {
      it('should call filesControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test filesControllerUpdate
        //instance.filesControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
