/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddItemToPlaylistDto model module.
 * @module model/AddItemToPlaylistDto
 * @version 1.0
 */
class AddItemToPlaylistDto {
    /**
     * Constructs a new <code>AddItemToPlaylistDto</code>.
     * @alias module:model/AddItemToPlaylistDto
     * @param fileId {Number} 
     * @param position {Number} 
     * @param duration {Number} 
     */
    constructor(fileId, position, duration) { 
        
        AddItemToPlaylistDto.initialize(this, fileId, position, duration);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fileId, position, duration) { 
        obj['fileId'] = fileId;
        obj['position'] = position;
        obj['duration'] = duration;
    }

    /**
     * Constructs a <code>AddItemToPlaylistDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddItemToPlaylistDto} obj Optional instance to populate.
     * @return {module:model/AddItemToPlaylistDto} The populated <code>AddItemToPlaylistDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddItemToPlaylistDto();

            if (data.hasOwnProperty('fileId')) {
                obj['fileId'] = ApiClient.convertToType(data['fileId'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddItemToPlaylistDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddItemToPlaylistDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddItemToPlaylistDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AddItemToPlaylistDto.RequiredProperties = ["fileId", "position", "duration"];

/**
 * @member {Number} fileId
 */
AddItemToPlaylistDto.prototype['fileId'] = undefined;

/**
 * @member {Number} position
 */
AddItemToPlaylistDto.prototype['position'] = undefined;

/**
 * @member {Number} duration
 */
AddItemToPlaylistDto.prototype['duration'] = undefined;






export default AddItemToPlaylistDto;

