/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateScreenDto model module.
 * @module model/CreateScreenDto
 * @version 1.0
 */
class CreateScreenDto {
    /**
     * Constructs a new <code>CreateScreenDto</code>.
     * @alias module:model/CreateScreenDto
     * @param name {String} 
     * @param location {String} 
     * @param fallbackFileId {Number} 
     */
    constructor(name, location, fallbackFileId) { 
        
        CreateScreenDto.initialize(this, name, location, fallbackFileId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, location, fallbackFileId) { 
        obj['name'] = name;
        obj['location'] = location;
        obj['fallbackFileId'] = fallbackFileId;
    }

    /**
     * Constructs a <code>CreateScreenDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateScreenDto} obj Optional instance to populate.
     * @return {module:model/CreateScreenDto} The populated <code>CreateScreenDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateScreenDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('fallbackFileId')) {
                obj['fallbackFileId'] = ApiClient.convertToType(data['fallbackFileId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateScreenDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateScreenDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateScreenDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }

        return true;
    }


}

CreateScreenDto.RequiredProperties = ["name", "location", "fallbackFileId"];

/**
 * @member {String} name
 */
CreateScreenDto.prototype['name'] = undefined;

/**
 * @member {String} location
 */
CreateScreenDto.prototype['location'] = undefined;

/**
 * @member {Number} fallbackFileId
 */
CreateScreenDto.prototype['fallbackFileId'] = undefined;






export default CreateScreenDto;

