/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.PlaylistItemEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlaylistItemEntity', function() {
    it('should create an instance of PlaylistItemEntity', function() {
      // uncomment below and update the code to test PlaylistItemEntity
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be.a(CmsApi.PlaylistItemEntity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property playlistId (base name: "playlistId")', function() {
      // uncomment below and update the code to test the property playlistId
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property fileId (base name: "fileId")', function() {
      // uncomment below and update the code to test the property fileId
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property playlist (base name: "playlist")', function() {
      // uncomment below and update the code to test the property playlist
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new CmsApi.PlaylistItemEntity();
      //expect(instance).to.be();
    });

  });

}));
