/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.ScreenStateEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScreenStateEntity', function() {
    it('should create an instance of ScreenStateEntity', function() {
      // uncomment below and update the code to test ScreenStateEntity
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be.a(CmsApi.ScreenStateEntity);
    });

    it('should have the property screenId (base name: "screenId")', function() {
      // uncomment below and update the code to test the property screenId
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property lastSync (base name: "lastSync")', function() {
      // uncomment below and update the code to test the property lastSync
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property lastPlaylistHash (base name: "lastPlaylistHash")', function() {
      // uncomment below and update the code to test the property lastPlaylistHash
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property currentIndex (base name: "currentIndex")', function() {
      // uncomment below and update the code to test the property currentIndex
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property visible (base name: "visible")', function() {
      // uncomment below and update the code to test the property visible
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property screen (base name: "screen")', function() {
      // uncomment below and update the code to test the property screen
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property currentPlaylist (base name: "currentPlaylist")', function() {
      // uncomment below and update the code to test the property currentPlaylist
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

    it('should have the property currentPlaylistId (base name: "currentPlaylistId")', function() {
      // uncomment below and update the code to test the property currentPlaylistId
      //var instance = new CmsApi.ScreenStateEntity();
      //expect(instance).to.be();
    });

  });

}));
