/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.UpdateScreenHeartbeatDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateScreenHeartbeatDto', function() {
    it('should create an instance of UpdateScreenHeartbeatDto', function() {
      // uncomment below and update the code to test UpdateScreenHeartbeatDto
      //var instance = new CmsApi.UpdateScreenHeartbeatDto();
      //expect(instance).to.be.a(CmsApi.UpdateScreenHeartbeatDto);
    });

    it('should have the property playerUrl (base name: "playerUrl")', function() {
      // uncomment below and update the code to test the property playerUrl
      //var instance = new CmsApi.UpdateScreenHeartbeatDto();
      //expect(instance).to.be();
    });

    it('should have the property visible (base name: "visible")', function() {
      // uncomment below and update the code to test the property visible
      //var instance = new CmsApi.UpdateScreenHeartbeatDto();
      //expect(instance).to.be();
    });

  });

}));
