/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddItemToPlaylistDto from './model/AddItemToPlaylistDto';
import AssignPlaylistDto from './model/AssignPlaylistDto';
import CreateFileDto from './model/CreateFileDto';
import CreatePlaylistDto from './model/CreatePlaylistDto';
import CreateScreenDto from './model/CreateScreenDto';
import FileEntity from './model/FileEntity';
import PlaylistEntity from './model/PlaylistEntity';
import PlaylistItemEntity from './model/PlaylistItemEntity';
import RecordLogDto from './model/RecordLogDto';
import ReorderPlaylistItemsDto from './model/ReorderPlaylistItemsDto';
import UpdateFileDto from './model/UpdateFileDto';
import UpdatePlaylistDto from './model/UpdatePlaylistDto';
import AppApi from './api/AppApi';
import FilesApi from './api/FilesApi';
import PlaylistsApi from './api/PlaylistsApi';
import ScreensApi from './api/ScreensApi';
import SyncApi from './api/SyncApi';


/**
* API dla ekranów.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CmsApi = require('index'); // See note below*.
* var xxxSvc = new CmsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CmsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CmsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CmsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddItemToPlaylistDto model constructor.
     * @property {module:model/AddItemToPlaylistDto}
     */
    AddItemToPlaylistDto,

    /**
     * The AssignPlaylistDto model constructor.
     * @property {module:model/AssignPlaylistDto}
     */
    AssignPlaylistDto,

    /**
     * The CreateFileDto model constructor.
     * @property {module:model/CreateFileDto}
     */
    CreateFileDto,

    /**
     * The CreatePlaylistDto model constructor.
     * @property {module:model/CreatePlaylistDto}
     */
    CreatePlaylistDto,

    /**
     * The CreateScreenDto model constructor.
     * @property {module:model/CreateScreenDto}
     */
    CreateScreenDto,

    /**
     * The FileEntity model constructor.
     * @property {module:model/FileEntity}
     */
    FileEntity,

    /**
     * The PlaylistEntity model constructor.
     * @property {module:model/PlaylistEntity}
     */
    PlaylistEntity,

    /**
     * The PlaylistItemEntity model constructor.
     * @property {module:model/PlaylistItemEntity}
     */
    PlaylistItemEntity,

    /**
     * The RecordLogDto model constructor.
     * @property {module:model/RecordLogDto}
     */
    RecordLogDto,

    /**
     * The ReorderPlaylistItemsDto model constructor.
     * @property {module:model/ReorderPlaylistItemsDto}
     */
    ReorderPlaylistItemsDto,

    /**
     * The UpdateFileDto model constructor.
     * @property {module:model/UpdateFileDto}
     */
    UpdateFileDto,

    /**
     * The UpdatePlaylistDto model constructor.
     * @property {module:model/UpdatePlaylistDto}
     */
    UpdatePlaylistDto,

    /**
    * The AppApi service constructor.
    * @property {module:api/AppApi}
    */
    AppApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The PlaylistsApi service constructor.
    * @property {module:api/PlaylistsApi}
    */
    PlaylistsApi,

    /**
    * The ScreensApi service constructor.
    * @property {module:api/ScreensApi}
    */
    ScreensApi,

    /**
    * The SyncApi service constructor.
    * @property {module:api/SyncApi}
    */
    SyncApi
};
