/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.PlaylistsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlaylistsApi', function() {
    describe('playlistsControllerAddItem', function() {
      it('should call playlistsControllerAddItem successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerAddItem
        //instance.playlistsControllerAddItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerCreate', function() {
      it('should call playlistsControllerCreate successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerCreate
        //instance.playlistsControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerDelete', function() {
      it('should call playlistsControllerDelete successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerDelete
        //instance.playlistsControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerFindAll', function() {
      it('should call playlistsControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerFindAll
        //instance.playlistsControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerFindById', function() {
      it('should call playlistsControllerFindById successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerFindById
        //instance.playlistsControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerGetRevision', function() {
      it('should call playlistsControllerGetRevision successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerGetRevision
        //instance.playlistsControllerGetRevision(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerRemoveItem', function() {
      it('should call playlistsControllerRemoveItem successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerRemoveItem
        //instance.playlistsControllerRemoveItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerReorderItems', function() {
      it('should call playlistsControllerReorderItems successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerReorderItems
        //instance.playlistsControllerReorderItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playlistsControllerUpdate', function() {
      it('should call playlistsControllerUpdate successfully', function(done) {
        //uncomment below and update the code to test playlistsControllerUpdate
        //instance.playlistsControllerUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
