/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.ScreensApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScreensApi', function() {
    describe('screensControllerAssignPlaylist', function() {
      it('should call screensControllerAssignPlaylist successfully', function(done) {
        //uncomment below and update the code to test screensControllerAssignPlaylist
        //instance.screensControllerAssignPlaylist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerCreate', function() {
      it('should call screensControllerCreate successfully', function(done) {
        //uncomment below and update the code to test screensControllerCreate
        //instance.screensControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerDelete', function() {
      it('should call screensControllerDelete successfully', function(done) {
        //uncomment below and update the code to test screensControllerDelete
        //instance.screensControllerDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerFindAll', function() {
      it('should call screensControllerFindAll successfully', function(done) {
        //uncomment below and update the code to test screensControllerFindAll
        //instance.screensControllerFindAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerFindById', function() {
      it('should call screensControllerFindById successfully', function(done) {
        //uncomment below and update the code to test screensControllerFindById
        //instance.screensControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerGenerateNewApiKey', function() {
      it('should call screensControllerGenerateNewApiKey successfully', function(done) {
        //uncomment below and update the code to test screensControllerGenerateNewApiKey
        //instance.screensControllerGenerateNewApiKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerGetByLocation', function() {
      it('should call screensControllerGetByLocation successfully', function(done) {
        //uncomment below and update the code to test screensControllerGetByLocation
        //instance.screensControllerGetByLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerHeartbeat', function() {
      it('should call screensControllerHeartbeat successfully', function(done) {
        //uncomment below and update the code to test screensControllerHeartbeat
        //instance.screensControllerHeartbeat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerRemovePlaylist', function() {
      it('should call screensControllerRemovePlaylist successfully', function(done) {
        //uncomment below and update the code to test screensControllerRemovePlaylist
        //instance.screensControllerRemovePlaylist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('screensControllerUpdateAssignment', function() {
      it('should call screensControllerUpdateAssignment successfully', function(done) {
        //uncomment below and update the code to test screensControllerUpdateAssignment
        //instance.screensControllerUpdateAssignment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
