/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CmsApi);
  }
}(this, function(expect, CmsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CmsApi.SyncApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SyncApi', function() {
    describe('syncControllerCheckManifestChanged', function() {
      it('should call syncControllerCheckManifestChanged successfully', function(done) {
        //uncomment below and update the code to test syncControllerCheckManifestChanged
        //instance.syncControllerCheckManifestChanged(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerGetFallback', function() {
      it('should call syncControllerGetFallback successfully', function(done) {
        //uncomment below and update the code to test syncControllerGetFallback
        //instance.syncControllerGetFallback(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerGetLogs', function() {
      it('should call syncControllerGetLogs successfully', function(done) {
        //uncomment below and update the code to test syncControllerGetLogs
        //instance.syncControllerGetLogs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerGetManifest', function() {
      it('should call syncControllerGetManifest successfully', function(done) {
        //uncomment below and update the code to test syncControllerGetManifest
        //instance.syncControllerGetManifest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerHeartbeat', function() {
      it('should call syncControllerHeartbeat successfully', function(done) {
        //uncomment below and update the code to test syncControllerHeartbeat
        //instance.syncControllerHeartbeat(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerRecordLog', function() {
      it('should call syncControllerRecordLog successfully', function(done) {
        //uncomment below and update the code to test syncControllerRecordLog
        //instance.syncControllerRecordLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('syncControllerUpdateScreenState', function() {
      it('should call syncControllerUpdateScreenState successfully', function(done) {
        //uncomment below and update the code to test syncControllerUpdateScreenState
        //instance.syncControllerUpdateScreenState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
