/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddItemToPlaylistDto from '../model/AddItemToPlaylistDto';
import CreatePlaylistDto from '../model/CreatePlaylistDto';
import PlaylistEntity from '../model/PlaylistEntity';
import PlaylistItemEntity from '../model/PlaylistItemEntity';
import ReorderPlaylistItemsDto from '../model/ReorderPlaylistItemsDto';
import UpdatePlaylistDto from '../model/UpdatePlaylistDto';

/**
* Playlists service.
* @module api/PlaylistsApi
* @version 1.0
*/
export default class PlaylistsApi {

    /**
    * Constructs a new PlaylistsApi. 
    * @alias module:api/PlaylistsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the playlistsControllerAddItem operation.
     * @callback module:api/PlaylistsApi~playlistsControllerAddItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistItemEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/AddItemToPlaylistDto} addItemToPlaylistDto 
     * @param {module:api/PlaylistsApi~playlistsControllerAddItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistItemEntity}
     */
    playlistsControllerAddItem(id, addItemToPlaylistDto, callback) {
      let postBody = addItemToPlaylistDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerAddItem");
      }
      // verify the required parameter 'addItemToPlaylistDto' is set
      if (addItemToPlaylistDto === undefined || addItemToPlaylistDto === null) {
        throw new Error("Missing the required parameter 'addItemToPlaylistDto' when calling playlistsControllerAddItem");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlaylistItemEntity;
      return this.apiClient.callApi(
        '/playlists/{id}/items', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerCreate operation.
     * @callback module:api/PlaylistsApi~playlistsControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/CreatePlaylistDto} createPlaylistDto 
     * @param {module:api/PlaylistsApi~playlistsControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistEntity}
     */
    playlistsControllerCreate(createPlaylistDto, callback) {
      let postBody = createPlaylistDto;
      // verify the required parameter 'createPlaylistDto' is set
      if (createPlaylistDto === undefined || createPlaylistDto === null) {
        throw new Error("Missing the required parameter 'createPlaylistDto' when calling playlistsControllerCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlaylistEntity;
      return this.apiClient.callApi(
        '/playlists', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerDelete operation.
     * @callback module:api/PlaylistsApi~playlistsControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/PlaylistsApi~playlistsControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    playlistsControllerDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/playlists/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerFindAll operation.
     * @callback module:api/PlaylistsApi~playlistsControllerFindAllCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PlaylistEntity>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/PlaylistsApi~playlistsControllerFindAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PlaylistEntity>}
     */
    playlistsControllerFindAll(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PlaylistEntity];
      return this.apiClient.callApi(
        '/playlists', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerFindById operation.
     * @callback module:api/PlaylistsApi~playlistsControllerFindByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/PlaylistsApi~playlistsControllerFindByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistEntity}
     */
    playlistsControllerFindById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerFindById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PlaylistEntity;
      return this.apiClient.callApi(
        '/playlists/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerGetRevision operation.
     * @callback module:api/PlaylistsApi~playlistsControllerGetRevisionCallback
     * @param {String} error Error message, if any.
     * @param {Number} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/PlaylistsApi~playlistsControllerGetRevisionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Number}
     */
    playlistsControllerGetRevision(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerGetRevision");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = 'Number';
      return this.apiClient.callApi(
        '/playlists/{id}/revision', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerRemoveItem operation.
     * @callback module:api/PlaylistsApi~playlistsControllerRemoveItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {Number} itemId 
     * @param {module:api/PlaylistsApi~playlistsControllerRemoveItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    playlistsControllerRemoveItem(id, itemId, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerRemoveItem");
      }
      // verify the required parameter 'itemId' is set
      if (itemId === undefined || itemId === null) {
        throw new Error("Missing the required parameter 'itemId' when calling playlistsControllerRemoveItem");
      }

      let pathParams = {
        'id': id,
        'itemId': itemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/playlists/{id}/items/{itemId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerReorderItems operation.
     * @callback module:api/PlaylistsApi~playlistsControllerReorderItemsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/ReorderPlaylistItemsDto} reorderPlaylistItemsDto 
     * @param {module:api/PlaylistsApi~playlistsControllerReorderItemsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    playlistsControllerReorderItems(id, reorderPlaylistItemsDto, callback) {
      let postBody = reorderPlaylistItemsDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerReorderItems");
      }
      // verify the required parameter 'reorderPlaylistItemsDto' is set
      if (reorderPlaylistItemsDto === undefined || reorderPlaylistItemsDto === null) {
        throw new Error("Missing the required parameter 'reorderPlaylistItemsDto' when calling playlistsControllerReorderItems");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/playlists/{id}/reorder', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the playlistsControllerUpdate operation.
     * @callback module:api/PlaylistsApi~playlistsControllerUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PlaylistEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/UpdatePlaylistDto} updatePlaylistDto 
     * @param {module:api/PlaylistsApi~playlistsControllerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PlaylistEntity}
     */
    playlistsControllerUpdate(id, updatePlaylistDto, callback) {
      let postBody = updatePlaylistDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling playlistsControllerUpdate");
      }
      // verify the required parameter 'updatePlaylistDto' is set
      if (updatePlaylistDto === undefined || updatePlaylistDto === null) {
        throw new Error("Missing the required parameter 'updatePlaylistDto' when calling playlistsControllerUpdate");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PlaylistEntity;
      return this.apiClient.callApi(
        '/playlists/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
