/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AssignPlaylistDto from '../model/AssignPlaylistDto';
import CreateScreenDto from '../model/CreateScreenDto';

/**
* Screens service.
* @module api/ScreensApi
* @version 1.0
*/
export default class ScreensApi {

    /**
    * Constructs a new ScreensApi. 
    * @alias module:api/ScreensApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the screensControllerAssignPlaylist operation.
     * @callback module:api/ScreensApi~screensControllerAssignPlaylistCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/AssignPlaylistDto} assignPlaylistDto 
     * @param {module:api/ScreensApi~screensControllerAssignPlaylistCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerAssignPlaylist(id, assignPlaylistDto, callback) {
      let postBody = assignPlaylistDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerAssignPlaylist");
      }
      // verify the required parameter 'assignPlaylistDto' is set
      if (assignPlaylistDto === undefined || assignPlaylistDto === null) {
        throw new Error("Missing the required parameter 'assignPlaylistDto' when calling screensControllerAssignPlaylist");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}/playlists', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerCreate operation.
     * @callback module:api/ScreensApi~screensControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/CreateScreenDto} createScreenDto 
     * @param {module:api/ScreensApi~screensControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerCreate(createScreenDto, callback) {
      let postBody = createScreenDto;
      // verify the required parameter 'createScreenDto' is set
      if (createScreenDto === undefined || createScreenDto === null) {
        throw new Error("Missing the required parameter 'createScreenDto' when calling screensControllerCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerDelete operation.
     * @callback module:api/ScreensApi~screensControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ScreensApi~screensControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerFindAll operation.
     * @callback module:api/ScreensApi~screensControllerFindAllCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/ScreensApi~screensControllerFindAllCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerFindAll(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerFindById operation.
     * @callback module:api/ScreensApi~screensControllerFindByIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ScreensApi~screensControllerFindByIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerFindById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerFindById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerGenerateNewApiKey operation.
     * @callback module:api/ScreensApi~screensControllerGenerateNewApiKeyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ScreensApi~screensControllerGenerateNewApiKeyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerGenerateNewApiKey(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerGenerateNewApiKey");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}/api-key', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerGetByLocation operation.
     * @callback module:api/ScreensApi~screensControllerGetByLocationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} location 
     * @param {module:api/ScreensApi~screensControllerGetByLocationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerGetByLocation(location, callback) {
      let postBody = null;
      // verify the required parameter 'location' is set
      if (location === undefined || location === null) {
        throw new Error("Missing the required parameter 'location' when calling screensControllerGetByLocation");
      }

      let pathParams = {
        'location': location
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/location/{location}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerHeartbeat operation.
     * @callback module:api/ScreensApi~screensControllerHeartbeatCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ScreensApi~screensControllerHeartbeatCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerHeartbeat(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerHeartbeat");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}/heartbeat', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerRemovePlaylist operation.
     * @callback module:api/ScreensApi~screensControllerRemovePlaylistCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {Number} playlistId 
     * @param {module:api/ScreensApi~screensControllerRemovePlaylistCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerRemovePlaylist(id, playlistId, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerRemovePlaylist");
      }
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling screensControllerRemovePlaylist");
      }

      let pathParams = {
        'id': id,
        'playlistId': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}/playlists/{playlistId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the screensControllerUpdateAssignment operation.
     * @callback module:api/ScreensApi~screensControllerUpdateAssignmentCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {Number} playlistId 
     * @param {module:api/ScreensApi~screensControllerUpdateAssignmentCallback} callback The callback function, accepting three arguments: error, data, response
     */
    screensControllerUpdateAssignment(id, playlistId, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling screensControllerUpdateAssignment");
      }
      // verify the required parameter 'playlistId' is set
      if (playlistId === undefined || playlistId === null) {
        throw new Error("Missing the required parameter 'playlistId' when calling screensControllerUpdateAssignment");
      }

      let pathParams = {
        'id': id,
        'playlistId': playlistId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/screens/{id}/playlists/{playlistId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
