/**
 * CMS API
 * API dla ekranów
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RecordLogDto from '../model/RecordLogDto';
import UpdateScreenHeartbeatDto from '../model/UpdateScreenHeartbeatDto';
import UpdateScreenStateDto from '../model/UpdateScreenStateDto';

/**
* Sync service.
* @module api/SyncApi
* @version 1.0
*/
export default class SyncApi {

    /**
    * Constructs a new SyncApi. 
    * @alias module:api/SyncApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the syncControllerCheckManifestChanged operation.
     * @callback module:api/SyncApi~syncControllerCheckManifestChangedCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {Number} currentRevision 
     * @param {module:api/SyncApi~syncControllerCheckManifestChangedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    syncControllerCheckManifestChanged(screenId, currentRevision, callback) {
      let postBody = null;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerCheckManifestChanged");
      }
      // verify the required parameter 'currentRevision' is set
      if (currentRevision === undefined || currentRevision === null) {
        throw new Error("Missing the required parameter 'currentRevision' when calling syncControllerCheckManifestChanged");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
        'currentRevision': currentRevision
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/sync/{screenId}/check', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerGetFallback operation.
     * @callback module:api/SyncApi~syncControllerGetFallbackCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {module:api/SyncApi~syncControllerGetFallbackCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    syncControllerGetFallback(screenId, callback) {
      let postBody = null;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerGetFallback");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/sync/{screenId}/fallback', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerGetLogs operation.
     * @callback module:api/SyncApi~syncControllerGetLogsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {module:api/SyncApi~syncControllerGetLogsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    syncControllerGetLogs(screenId, callback) {
      let postBody = null;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerGetLogs");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Object];
      return this.apiClient.callApi(
        '/sync/{screenId}/logs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerGetManifest operation.
     * @callback module:api/SyncApi~syncControllerGetManifestCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} xScreenID Screen identifier
     * @param {Object} opts Optional parameters
     * @param {Number} [sinceRevision] 
     * @param {module:api/SyncApi~syncControllerGetManifestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    syncControllerGetManifest(xScreenID, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'xScreenID' is set
      if (xScreenID === undefined || xScreenID === null) {
        throw new Error("Missing the required parameter 'xScreenID' when calling syncControllerGetManifest");
      }

      let pathParams = {
      };
      let queryParams = {
        'sinceRevision': opts['sinceRevision']
      };
      let headerParams = {
        'X-Screen-ID': xScreenID
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/sync/manifest', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerHeartbeat operation.
     * @callback module:api/SyncApi~syncControllerHeartbeatCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {module:model/UpdateScreenHeartbeatDto} updateScreenHeartbeatDto 
     * @param {module:api/SyncApi~syncControllerHeartbeatCallback} callback The callback function, accepting three arguments: error, data, response
     */
    syncControllerHeartbeat(screenId, updateScreenHeartbeatDto, callback) {
      let postBody = updateScreenHeartbeatDto;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerHeartbeat");
      }
      // verify the required parameter 'updateScreenHeartbeatDto' is set
      if (updateScreenHeartbeatDto === undefined || updateScreenHeartbeatDto === null) {
        throw new Error("Missing the required parameter 'updateScreenHeartbeatDto' when calling syncControllerHeartbeat");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/sync/{screenId}/heartbeat', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerRecordLog operation.
     * @callback module:api/SyncApi~syncControllerRecordLogCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {module:model/RecordLogDto} recordLogDto 
     * @param {module:api/SyncApi~syncControllerRecordLogCallback} callback The callback function, accepting three arguments: error, data, response
     */
    syncControllerRecordLog(screenId, recordLogDto, callback) {
      let postBody = recordLogDto;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerRecordLog");
      }
      // verify the required parameter 'recordLogDto' is set
      if (recordLogDto === undefined || recordLogDto === null) {
        throw new Error("Missing the required parameter 'recordLogDto' when calling syncControllerRecordLog");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/sync/{screenId}/logs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the syncControllerUpdateScreenState operation.
     * @callback module:api/SyncApi~syncControllerUpdateScreenStateCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} screenId 
     * @param {module:model/UpdateScreenStateDto} updateScreenStateDto 
     * @param {module:api/SyncApi~syncControllerUpdateScreenStateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    syncControllerUpdateScreenState(screenId, updateScreenStateDto, callback) {
      let postBody = updateScreenStateDto;
      // verify the required parameter 'screenId' is set
      if (screenId === undefined || screenId === null) {
        throw new Error("Missing the required parameter 'screenId' when calling syncControllerUpdateScreenState");
      }
      // verify the required parameter 'updateScreenStateDto' is set
      if (updateScreenStateDto === undefined || updateScreenStateDto === null) {
        throw new Error("Missing the required parameter 'updateScreenStateDto' when calling syncControllerUpdateScreenState");
      }

      let pathParams = {
        'screenId': screenId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/sync/{screenId}/state', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
